#!/bin/bash

if [[ -z "$1" ]]; then
    echo "Example usage: $ ./aoc 1" 1>&2
    exit 1
fi

mkdir -p ./build

mops install &&\
"$(dfx cache show)/moc" -wasi-system-api "src/$1.mo" -o "build/$1.wasm" $(mops sources) &&\
wasmtime -S preview2=n -C cache=n -W bulk-memory -W multi-memory "build/$1.wasm"
